spring:
  application:
    name: eureka-client1

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/
  instance:
    hostname: client1

