server:
  port: 1000

spring:
  application:
    name: client-customer

eureka:
  instance:
    hostname: client-customer
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/

#springboot  的监控端点访问权限，*表示所有的访问端点都允许访问
management:
  endpoints:
    web:
      exposure:
        include: ['health','info','hystrix.stream']
