server:
  port: 1234

spring:
  application:
    name: springcloud-zuul

zuul:
  routes:
    aaa:
      path: /api-zuul/**
      serviceId: client-customer
      #url: http://localhost:1000/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/