
spring:
  application:
    name: eureka-server

server:
  port: 8080

eureka:
  instance:
    hostname: server1
  client:
    register-with-eureka: false #是否将自己注册到eureka-Server中
    fetch-registry: false #是否从eureka-Server中获取服务注册信息
    service-url:
      defaultZone: http://localhost:8090/erueka/
  server:
    enable-self-preservation: false #关闭自我保护机制，保证不可用的服务被及时剔除
    eviction-interval-timer-in-ms: 5000 #5秒内没有收到服务心跳，就剔除该服务