spring:
  application:
    name: springcloud-feign1

server:
  port: 2010

eureka:
  instance:
    hostname: springcloud-feign1
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8090/eureka/


feign:
  hystrix:
    enabled: true  #开启服务熔断
