spring:
  application:
    name: eureka-server2

server:
  port: 8090

eureka:
  instance:
    hostname: server2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8080/eureka/